### ISSUE TITLE
JSON serialization for signature check does not match Chaperone

### ISSUE THREAD

**Issue by mjbrisebois** [Holo-Host/servicelogger#19]
Chaperone is using `json-stable-stringify` (https://www.npmjs.com/package/json-stable-stringify), which sorts the keys alphabetically.

This appears to be a simple solution https://stackoverflow.com/questions/42723065/how-to-sort-hashmap-keys-when-serializing-with-serde/42723390#42723390

**Comment by yegortimoshenko** [comment]
> This appears to be a simple solution https://stackoverflow.com/questions/42723065/how-to-sort-hashmap-keys-when-serializing-with-serde/42723390#42723390

Indeed. Although, it would make more sense to store data in `BTreeMap` in the first place, rather than cast `HashMap` into `BTreeMap` during serialization.

**Comment by mjbrisebois** [comment]
CC @yegortimoshenko 

These to JSON conversions are where we need sorted keys to be consistent with Chaperone.

- https://github.com/Holo-Host/servicelogger/blob/master/zomes/service/code/src/request.rs#L90
- https://github.com/Holo-Host/servicelogger/blob/master/zomes/service/code/src/servicelog.rs#L68

**Comment by mjbrisebois** [comment]
Solved by reordering struct properties

**Comment by mjbrisebois** [comment]
Reopening issue until there is a scenario test to ensure the struct property order is preserved.

**Comment by mjbrisebois** [comment]
Scenario test - https://github.com/Holo-Host/servicelogger/blob/master/test/basic.js#L28-L60
